### ISSUE TITLE
Spelling mistakes on Focus action options

### ISSUE THREAD

**Issue by pjbisset** [bitfocus/companion-module-birddog-visca#9]
I'm running v2.1.1 of Companion.

The Focus action has two spelling mistakes in its list of options:

Forcus Stop
Forcus One Push Auto

I think they should be Focus.

**Comment by BenniMTools** [comment]
Hi,
it's fixed in the latest version.

Best,
benni

**Comment by pjbisset** [comment]
This was not included in latest release of companion - 2.1.4. Still shows Forcus Stop and Forcus One Push Auto.
